cache: cargo
language: rust
os:
  - linux
  - osx
rust:
  - nightly
matrix:
  allow_failures:
    - rust: stable
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xorg-dev; fi
script:
  - cargo build --verbose --lib
  - cargo build --verbose --example reference
branches:
  only:
  - master