[package]
name = "smallpt"
version = "0.3.2"
license = "MIT"
description = "A small ray/pathtracer in Rust, inspired by Kevin Beason's educational 99-lines ray/pathtracer (http://www.kevinbeason.com/smallpt/)"
keywords = ["raytracer", "raytracing", "ray-tracing", "path-tracer"]
authors = ["Colin Barré-Brisebois <colinbb@gmail.com>"]
categories = ["rendering"]
repository = "https://github.com/zigguratvertigo/smallpt-rs"
readme = "README.md"
build = "build.rs"
exclude = ["images/*"]

[badges]
travis-ci = { repository = "zigguratvertigo/smallpt-rs" }

[dependencies]
rayon = "1.0.3"
rand = "0.6"
num_cpus = "1.9.0"
log = "0.4.6"
nalgebra = "0.16"
bvh = "0.2.4"

[dev-dependencies]
minifb = "0.11.2"
structopt = "0.2.14"

[build-dependencies.mml]
version = "0.1"