[package]
name = "smallpt"
version = "0.1.1"
license = "MIT"
description = "A rust on a small ray/pathtracer, inspired from Kevin Beason's educational 99-lines ray/pathtracer (http://www.kevinbeason.com/smallpt/)"
keywords = ["raytracer", "raytracing", "ray-tracing", "path-tracer"]
authors = ["Colin Barré-Brisebois <colinbb@gmail.com>"]
categories = ["rendering"]
repository = "https://github.com/zigguratvertigo/smallpt-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "https://travis-ci.com/zigguratvertigo/smallpt-rs", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
rayon = "1.0"
structopt = "0.2"
cgmath = "0.16.1"
rand = "0.5.0"
num_cpus = "1.8.0"
minifb = "0.10.6"

[[bin]]
name = "reference"
path = "examples/reference.rs"