[package]
name = "smallpt"
version = "0.1.0"
license = "MIT/Apache-2.0"
description = "A rust implementation of Kevin Beason's educational 100 lines small ray/pathtracer http://www.kevinbeason.com/smallpt/"
keywords = ["raytracer", "raytracing", "ray-tracing", "path-tracer"]
authors = ["Colin Barré-Brisebois <colinbb@gmail.com>"]
categories = ["rendering"]
repository = "https://github.com/zigguratvertigo/smallpt-rs"
readme = "README.md"

[dependencies]
rayon = "1.0"
structopt = "0.2"
cgmath = "0.16.1"
rand = "*"
num_cpus = "1.8.0"
minifb = "0.10.6"
#smallpt = { path = "../smallpt-rs" }

[[bin]]
name = "example1"
path = "examples/example1.rs"