[package]
name = "smallpt"
version = "0.1.0"
license = "MIT/Apache-2.0"
description = "A rust implementation of Kevin Beason's educational 100 lines small ray/pathtracer http://www.kevinbeason.com/smallpt/"
keywords = ["raytracer", "ray tracing", "raytracing", "ray-tracing", "path-tracer"]
authors = ["Colin Barré-Brisebois <colinbb@gmail.com>"]
categories = ["rendering"]
repository = "https://github.com/zigguratvertigo/smallpt-rs"
readme = "README.md"

[dependencies]
rand = "*"
num_cpus = "1.8.0"
cgmath = "0.16.1"
minifb = "0.10.6"
rayon = "1.0"
structopt = "0.2"